//This will allow to use loader in our react file globally by dispatching the showLoader and hideLoader actions, and the state of the loader can be accessed from the Redux store to conditionally render a loading spinner or other UI elements based on whether the loader is active or not. We won't have to create loader state for each component separately, instead we can manage the loader state globally using this loaderSlice, which will make our code cleaner and more maintainable.

import { createSlice } from "@reduxjs/toolkit";

const loaderSlice = createSlice({
  name: "loader", //name for the slice of state that this reducer will manage. This name is used to identify the slice in the Redux store and when dispatching actions.
  initialState: {
    loader: false, //initial state of the loader, which is set to false indicating that the loader is not active by default.
  },
  reducers: {
    showLoader: (state) => {
      state.loader = true; //This reducer function is responsible for showing the loader. When this action is dispatched, it sets the loading property of the state to true, indicating that the loader should be displayed.
    },
    hideLoader: (state) => {
      state.loader = false; //This reducer function is responsible for hiding the loader. When this action is dispatched, it sets the loading property of the state to false, indicating that the loader should be hidden.
    },
  },
});

export const { showLoader, hideLoader } = loaderSlice.actions; //This line exports the action creators generated by createSlice for the showLoader and hideLoader reducers. These action creators can be used to dispatch actions that will trigger the corresponding reducer functions to update the state of the loader in the Redux store.
export default loaderSlice.reducer; //This line exports the reducer function generated by createSlice for the loader slice. This reducer function will be used to handle actions related to showing and hiding the loader, and it will be combined with other reducers in the Redux store to manage the overall state of the application.
