import { createSlice } from "@reduxjs/toolkit";

const userSlice = createSlice({
  name: "user",
  initialState: {
    user: null, //initial state of the user, which is set to null indicating that there is no user logged in by default.
    allUsers: [],
    allChats: [], //initial state of all users, which is set to an empty array indicating that there are no users fetched from the server by default.
    selectedChat: null, //On default no chat is selected when user clicks on chat then only that chat will get selected.
    lastIncomingMessage: null,
  },
  reducers: {
    setUser: (state, action) => {
      state.user = action.payload; //This reducer function is responsible for setting the user information in the state. When this action is dispatched, it takes the payload (which should contain the user information) and assigns it to the user property of the state, effectively updating the state with the logged-in user's information.
    },
    clearUser: (state) => {
      state.user = null; //This reducer function is responsible for clearing the user information from the state. When this action is dispatched, it sets the user property of the state back to null, indicating that there is no user currently logged in.
    },
    setAllUsers: (state, action) => {
      state.allUsers = action.payload; //This reducer function is responsible for setting the list of all users in the state. When this action is dispatched, it takes the payload (which should contain the list of all users) and assigns it to the allUsers property of the state, effectively updating the state with the fetched list of users from the server.
    },
    setAllChats: (state, action) => {
      state.allChats = action.payload;
    },
    setSelectedChat: (state, action) => {
      state.selectedChat = action.payload;
    },
    setLastIncomingMessage: (state, action) => {
      state.lastIncomingMessage = action.payload;
    },
  },
});

export const {
  setUser,
  clearUser,
  setAllUsers,
  setAllChats,
  setSelectedChat,
  setLastIncomingMessage,
} = userSlice.actions;
export default userSlice.reducer; //This line exports the reducer function generated by createSlice for the user slice. This reducer function will be used to handle actions related to setting and clearing the user information in the Redux store, and it will be combined with other reducers in the Redux store to manage the overall state of the application.
